packages:
  - docs
  - playground
  - apps/**
  - packages/**
  - examples/*
  - '!packages/x-dev-tools/templates/**'

catalog:
  '@antfu/eslint-config': ^3.0.0
  '@iconify-json/carbon': ^1.1.37
  '@nuxt/devtools': ^1.3.14
  '@nuxt/kit': ^3.15.2
  '@nuxt/schema': ^3.15.2
  '@types/fs-extra': ^11.0.4
  '@types/node': ^22.5.0
  '@unocss/nuxt': ^0.64.0
  '@unocss/preset-web-fonts': ^0.64.0
  '@unocss/core': ^0.64.0
  '@unocss/preset-mini': ^0.64.0
  '@unocss/preset-icons': ^0.64.0
  '@vitejs/plugin-vue': ^5.2.1
  '@vueuse/core': ^11.2.0
  '@vue/tsconfig': ^0.7.0
  tsx: ^4.19.2
  magic-color: ^2.0.0
  element-plus: ^2.8.7
  unplugin-auto-import: ^0.18.3
  unplugin-vue-components: ^0.27.4
  unplugin-element-plus: ^0.8.0
  vue-tsc: ^2.2.0
  unocss: ^0.64.0
  unocss-transformer-alias: ^0.0.8
  bumpp: ^9.5.2
  consola: ^3.2.3
  esno: ^4.7.0
  execa: ^8.0.1
  fs-extra: ^11.2.0
  lint-staged: ^15.2.9
  nuxt: ^3.15.2
  hono: ^4.7.10
  ofetch: ^1.3.4
  pathe: ^1.1.2
  simple-git: ^3.25.0
  floating-vue: ^5.2.2
  simple-git-hooks: ^2.11.1
  std-env: ^3.7.0
  taze: ^0.16.6
  typescript: ~5.6
  unbuild: ^2.0.0
  vitepress: ^1.3.3
  vitepress-plugin-group-icons: ^1.0.3
  vitest: ^2.0.5
  vue: ^3.5.13
  vite: ^5.4.10
  vue-flow-layout: ^0.1.1
  vite-plugin-dts: ^4.3.0
  vue-router: latest
