export { default as book } from './book'
export { default as upload } from './upload'
export { default as ssr } from './ssr'
export { default as user } from './user'
export { default as sms } from './sms'
export { default as signup } from './signup'
export { default as otp } from './otp'
export { default as login } from './login'
